// BED
import bed1 from "../assets/bed/bed1.jpg";
import bed2 from "../assets/bed/bed2.jpg";
import bed3 from "../assets/bed/bed3.jpg";
import bed4 from "../assets/bed/bed4.jpg";
import bed5 from "../assets/bed/bed5.jpg";
import bed6 from "../assets/bed/bed6.jpg";
import bed7 from "../assets/bed/bed7.jpg";
import bed8 from "../assets/bed/bed8.jpg";
import bed9 from "../assets/bed/bed9.jpg";
import bed10 from "../assets/bed/bed10.jpg";

// CAMERA
import cam1 from "../assets/camera/cam1.jpg";
import cam2 from "../assets/camera/cam2.jpg";
import cam3 from "../assets/camera/cam3.jpg";
import cam4 from "../assets/camera/cam4.jpg";
import cam5 from "../assets/camera/cam5.jpg";
import cam6 from "../assets/camera/cam6.jpg";
import cam7 from "../assets/camera/cam7.jpg";
import cam8 from "../assets/camera/cam8.jpg";
import cam9 from "../assets/camera/cam9.jpg";
import cam10 from "../assets/camera/cam10.jpg";

// FRIDGE
import fridge1 from "../assets/fridge/fridge1.jpg";
import fridge2 from "../assets/fridge/fridge2.jpg";
import fridge3 from "../assets/fridge/fridge3.jpg";
import fridge4 from "../assets/fridge/fridge4.jpg";
import fridge5 from "../assets/fridge/fridge5.jpg";
import fridge6 from "../assets/fridge/fridge6.jpg";
import fridge7 from "../assets/fridge/fridge7.jpg";
import fridge8 from "../assets/fridge/fridge8.jpg";
import fridge9 from "../assets/fridge/fridge9.jpg";
import fridge10 from "../assets/fridge/fridge10.jpg";

// SOFA
import sofa1 from "../assets/sofa/sofa1.jpg";
import sofa2 from "../assets/sofa/sofa2.jpg";
import sofa3 from "../assets/sofa/sofa3.jpg";
import sofa4 from "../assets/sofa/sofa4.jpg";
import sofa5 from "../assets/sofa/sofa5.jpg";
import sofa6 from "../assets/sofa/sofa6.jpg";
import sofa7 from "../assets/sofa/sofa7.jpg";
import sofa8 from "../assets/sofa/sofa8.jpg";
import sofa9 from "../assets/sofa/sofa9.jpg";
import sofa10 from "../assets/sofa/sofa10.jpg";

export const data = [
  // BEDS
  {
    id: 1,
    userId: "user1",
    productName: "Bed 1",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Like New",
    description: "Comfortable wooden bed.",
    image: bed1,
    pricePerDay: 150,
    securityDeposit: 2000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 2,
    userId: "user2",
    productName: "Bed 2",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Good",
    description: "Premium bedroom bed.",
    image: bed2,
    pricePerDay: 140,
    securityDeposit: 1900,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 3,
    userId: "user3",
    productName: "Bed 3",
    brand: "SleepWell",
    category: "Furniture",
    condition: "New",
    description: "Luxury king size bed.",
    image: bed3,
    pricePerDay: 180,
    securityDeposit: 2300,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
  },
  {
    id: 4,
    userId: "user1",
    productName: "Bed 4",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Good",
    description: "Strong durable bed.",
    image: bed4,
    pricePerDay: 130,
    securityDeposit: 1800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 5,
    userId: "user2",
    productName: "Bed 5",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Like New",
    description: "Modern wooden bed.",
    image: bed5,
    pricePerDay: 160,
    securityDeposit: 2100,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
  },
  {
    id: 6,
    userId: "user3",
    productName: "Bed 6",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Good",
    description: "Minimal style bed.",
    image: bed6,
    pricePerDay: 120,
    securityDeposit: 1700,
    totalStock: 4,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 7,
    userId: "user1",
    productName: "Bed 7",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Used",
    description: "Affordable bed option.",
    image: bed7,
    pricePerDay: 100,
    securityDeposit: 1500,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 8,
    userId: "user2",
    productName: "Bed 8",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Good",
    description: "Durable bedroom bed.",
    image: bed8,
    pricePerDay: 135,
    securityDeposit: 1800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 9,
    userId: "user3",
    productName: "Bed 9",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Like New",
    description: "Comfortable double bed.",
    image: bed9,
    pricePerDay: 155,
    securityDeposit: 2000,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
  },
  {
    id: 10,
    userId: "user1",
    productName: "Bed 10",
    brand: "SleepWell",
    category: "Furniture",
    condition: "Good",
    description: "Strong wooden bed.",
    image: bed10,
    pricePerDay: 145,
    securityDeposit: 1900,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },

  // CAMERAS
  {
    id: 11,
    userId: "user2",
    productName: "Camera 1",
    brand: "Canon",
    category: "Electronics",
    condition: "Like New",
    description: "Professional DSLR camera.",
    image: cam1,
    pricePerDay: 350,
    securityDeposit: 5000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
  },
  {
    id: 12,
    userId: "user3",
    productName: "Camera 2",
    brand: "Canon",
    category: "Electronics",
    condition: "Good",
    description: "High resolution camera.",
    image: cam2,
    pricePerDay: 320,
    securityDeposit: 4800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 13,
    userId: "user1",
    productName: "Camera 3",
    brand: "Sony",
    category: "Electronics",
    condition: "Like New",
    description: "Mirrorless camera.",
    image: cam3,
    pricePerDay: 380,
    securityDeposit: 5200,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
  },
  {
    id: 14,
    userId: "user2",
    productName: "Camera 4",
    brand: "Sony",
    category: "Electronics",
    condition: "Good",
    description: "Compact camera.",
    image: cam4,
    pricePerDay: 300,
    securityDeposit: 4500,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 15,
    userId: "user3",
    productName: "Camera 5",
    brand: "Nikon",
    category: "Electronics",
    condition: "Like New",
    description: "DSLR for photography.",
    image: cam5,
    pricePerDay: 360,
    securityDeposit: 5000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 16,
    userId: "user1",
    productName: "Camera 6",
    brand: "Nikon",
    category: "Electronics",
    condition: "Good",
    description: "HD camera.",
    image: cam6,
    pricePerDay: 310,
    securityDeposit: 4600,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 17,
    userId: "user2",
    productName: "Camera 7",
    brand: "Canon",
    category: "Electronics",
    condition: "Like New",
    description: "Advanced DSLR camera.",
    image: cam7,
    pricePerDay: 370,
    securityDeposit: 5100,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
  },
  {
    id: 18,
    userId: "user3",
    productName: "Camera 8",
    brand: "Sony",
    category: "Electronics",
    condition: "Good",
    description: "Mirrorless compact camera.",
    image: cam8,
    pricePerDay: 330,
    securityDeposit: 4800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 19,
    userId: "user1",
    productName: "Camera 9",
    brand: "Canon",
    category: "Electronics",
    condition: "Like New",
    description: "Photography DSLR.",
    image: cam9,
    pricePerDay: 360,
    securityDeposit: 5000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
  },
  {
    id: 20,
    userId: "user2",
    productName: "Camera 10",
    brand: "Nikon",
    category: "Electronics",
    condition: "Good",
    description: "Professional camera.",
    image: cam10,
    pricePerDay: 340,
    securityDeposit: 4700,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },

  // FRIDGES
  {
    id: 21,
    userId: "user1",
    productName: "Fridge 1",
    brand: "Samsung",
    category: "Appliances",
    condition: "Like New",
    description: "Double door refrigerator.",
    image: fridge1,
    pricePerDay: 220,
    securityDeposit: 4000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 22,
    userId: "user2",
    productName: "Fridge 2",
    brand: "LG",
    category: "Appliances",
    condition: "Good",
    description: "Energy efficient fridge.",
    image: fridge2,
    pricePerDay: 210,
    securityDeposit: 3800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 23,
    userId: "user3",
    productName: "Fridge 3",
    brand: "Samsung",
    category: "Appliances",
    condition: "Like New",
    description: "Large refrigerator.",
    image: fridge3,
    pricePerDay: 230,
    securityDeposit: 4200,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
  },
  {
    id: 24,
    userId: "user1",
    productName: "Fridge 4",
    brand: "LG",
    category: "Appliances",
    condition: "Good",
    description: "Modern fridge.",
    image: fridge4,
    pricePerDay: 200,
    securityDeposit: 3600,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 25,
    userId: "user2",
    productName: "Fridge 5",
    brand: "Whirlpool",
    category: "Appliances",
    condition: "Like New",
    description: "Spacious fridge.",
    image: fridge5,
    pricePerDay: 240,
    securityDeposit: 4300,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
  },
  {
    id: 26,
    userId: "user3",
    productName: "Fridge 6",
    brand: "Samsung",
    category: "Appliances",
    condition: "Good",
    description: "Cooling refrigerator.",
    image: fridge6,
    pricePerDay: 210,
    securityDeposit: 3900,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 27,
    userId: "user1",
    productName: "Fridge 7",
    brand: "LG",
    category: "Appliances",
    condition: "Like New",
    description: "Double door fridge.",
    image: fridge7,
    pricePerDay: 220,
    securityDeposit: 4000,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 28,
    userId: "user2",
    productName: "Fridge 8",
    brand: "Whirlpool",
    category: "Appliances",
    condition: "Good",
    description: "Energy saving fridge.",
    image: fridge8,
    pricePerDay: 200,
    securityDeposit: 3500,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 29,
    userId: "user3",
    productName: "Fridge 9",
    brand: "Samsung",
    category: "Appliances",
    condition: "Like New",
    description: "Modern refrigerator.",
    image: fridge9,
    pricePerDay: 235,
    securityDeposit: 4200,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
  },
  {
    id: 30,
    userId: "user1",
    productName: "Fridge 10",
    brand: "LG",
    category: "Appliances",
    condition: "Good",
    description: "Reliable fridge.",
    image: fridge10,
    pricePerDay: 205,
    securityDeposit: 3600,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },

  // SOFAS
  {
    id: 31,
    userId: "user2",
    productName: "Sofa 1",
    brand: "IKEA",
    category: "Furniture",
    condition: "Like New",
    description: "Comfortable living room sofa.",
    image: sofa1,
    pricePerDay: 180,
    securityDeposit: 2500,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
  },
  {
    id: 32,
    userId: "user3",
    productName: "Sofa 2",
    brand: "Urban Ladder",
    category: "Furniture",
    condition: "Good",
    description: "Stylish sofa.",
    image: sofa2,
    pricePerDay: 170,
    securityDeposit: 2400,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 33,
    userId: "user1",
    productName: "Sofa 3",
    brand: "IKEA",
    category: "Furniture",
    condition: "Like New",
    description: "Soft sofa.",
    image: sofa3,
    pricePerDay: 190,
    securityDeposit: 2600,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
  },
  {
    id: 34,
    userId: "user2",
    productName: "Sofa 4",
    brand: "Urban Ladder",
    category: "Furniture",
    condition: "Good",
    description: "Premium sofa.",
    image: sofa4,
    pricePerDay: 175,
    securityDeposit: 2450,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 35,
    userId: "user3",
    productName: "Sofa 5",
    brand: "IKEA",
    category: "Furniture",
    condition: "Like New",
    description: "Modern sofa.",
    image: sofa5,
    pricePerDay: 185,
    securityDeposit: 2550,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 36,
    userId: "user1",
    productName: "Sofa 6",
    brand: "Urban Ladder",
    category: "Furniture",
    condition: "Good",
    description: "Living room sofa.",
    image: sofa6,
    pricePerDay: 170,
    securityDeposit: 2400,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 37,
    userId: "user2",
    productName: "Sofa 7",
    brand: "IKEA",
    category: "Furniture",
    condition: "Like New",
    description: "Premium sofa set.",
    image: sofa7,
    pricePerDay: 200,
    securityDeposit: 2800,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
  },
  {
    id: 38,
    userId: "user3",
    productName: "Sofa 8",
    brand: "Urban Ladder",
    category: "Furniture",
    condition: "Good",
    description: "Comfortable sofa.",
    image: sofa8,
    pricePerDay: 175,
    securityDeposit: 2500,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
  {
    id: 39,
    userId: "user1",
    productName: "Sofa 9",
    brand: "IKEA",
    category: "Furniture",
    condition: "Like New",
    description: "Luxury sofa.",
    image: sofa9,
    pricePerDay: 210,
    securityDeposit: 2900,
    totalStock: 2,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: true,
    active: true,
  },
  {
    id: 40,
    userId: "user2",
    productName: "Sofa 10",
    brand: "Urban Ladder",
    category: "Furniture",
    condition: "Good",
    description: "Classic sofa.",
    image: sofa10,
    pricePerDay: 180,
    securityDeposit: 2600,
    totalStock: 3,
    availableFrom: "2026-03-01",
    availableTill: null,
    featured: false,
    active: true,
  },
];

